-- ============================================================
-- Seed 0003 · capa estratégica (programas + proyectos) — Fase 2
-- Generado por scripts/generar_seed_estrategico.py — no editar a mano.
-- Corre en el schema cmi (D43).
-- ============================================================
set search_path to cmi, public;

-- 100 programas
insert into programa (id, eje_codigo, nombre, objetivo) values (1, 'EJE-01', 'Política Urbana Integral y Gobernanza del Territorio', 'Establecer principios rectores y visión urbana compartida hasta 2050.');
insert into programa (id, eje_codigo, nombre, objetivo) values (2, 'EJE-01', 'Normativa Urbana y Convenios', 'Facilitar compromisos formales con sectores y territorios.');
insert into programa (id, eje_codigo, nombre, objetivo) values (3, 'EJE-01', 'Planificación Urbana Operativa', 'Monitorear el crecimiento y facilitar decisiones basadas en datos.');
insert into programa (id, eje_codigo, nombre, objetivo) values (4, 'EJE-01', 'Reforma Institucional y Gestión Municipal por Resultados', 'Implementar una organización orientada a la gestión territorial efectiva.');
insert into programa (id, eje_codigo, nombre, objetivo) values (5, 'EJE-01', 'Sistema de Recaudación Municipal', 'Promover cultura tributaria con beneficios y corresponsabilidad.');
insert into programa (id, eje_codigo, nombre, objetivo) values (6, 'EJE-01', 'Presupuesto y POA Transparente', 'Facilitar seguimiento de metas presupuestarias por distrito.');
insert into programa (id, eje_codigo, nombre, objetivo) values (7, 'EJE-01', 'Transparencia y Ética Pública Municipal', 'Plataforma de transparencia con datos abiertos e infografías.');
insert into programa (id, eje_codigo, nombre, objetivo) values (8, 'EJE-01', 'Participación y Control Social Organizado', 'Formar actores ciudadanos en fiscalización y seguimiento de obras.');
insert into programa (id, eje_codigo, nombre, objetivo) values (9, 'EJE-01', 'Auditoría Técnica y Evaluación Pública', 'Plataforma para validar calidad y avance de proyectos vecinales.');
insert into programa (id, eje_codigo, nombre, objetivo) values (10, 'EJE-01', 'Presupuesto Participativo y Contraloría Social', 'Implementar un proceso participativo, digital y deliberativo.');
insert into programa (id, eje_codigo, nombre, objetivo) values (11, 'EJE-01', 'Estrategia de Financiamiento Mixto y Fondos Fiduciarios', 'Crear un mecanismo ágil, auditable y transparente para canalizar inversión estructural.');
insert into programa (id, eje_codigo, nombre, objetivo) values (12, 'EJE-01', 'Estrategia de Financiamiento con participación Privada', 'Campaña multisectorial para atraer inversión en proyectos visibles.');
insert into programa (id, eje_codigo, nombre, objetivo) values (13, 'EJE-01', 'Gestión de Recursos Estatales y Cooperación Internacional', 'Agenda de proyectos presentada al Gobierno Nacional y multilaterales.');
insert into programa (id, eje_codigo, nombre, objetivo) values (14, 'EJE-01', 'Transformación Digital Ciudadana', 'Plataforma integral para interacción ciudadana, trámites, control social y servicios digitales');
insert into programa (id, eje_codigo, nombre, objetivo) values (15, 'EJE-02', 'Salud Primaria Integral', 'Consolidar centros de primer y segundo nivel con atención continua, insumos, y equipo humano.');
insert into programa (id, eje_codigo, nombre, objetivo) values (16, 'EJE-02', 'Salud Inteligente y Preventiva', 'Crear un sistema digital integrado de vigilancia epidemiológica y prevención.');
insert into programa (id, eje_codigo, nombre, objetivo) values (17, 'EJE-02', 'Salud Mental Comunitaria', 'Crear centros de atención emocional en todos los distritos.');
insert into programa (id, eje_codigo, nombre, objetivo) values (18, 'EJE-02', 'Deporte para la Vida (Formativo y comunitario)', 'Creación de 50 escuelas deportivas gratuitas en barrios populares con entrenadores formadores, acompañamiento emocional y articulación con unidades educativas.');
insert into programa (id, eje_codigo, nombre, objetivo) values (19, 'EJE-02', 'Deporte de Alto Rendimiento Paceño (Competitivo y de representación)', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (20, 'EJE-02', 'Control de Alimentos y Salud Nutricional', 'Implementar unidades de control sanitario y educación nutricional.');
insert into programa (id, eje_codigo, nombre, objetivo) values (21, 'EJE-02', 'Agua Segura y Gestión Hídrica', 'Generar brigadas de prevención, tanques de reserva, filtros, y control comunitario.');
insert into programa (id, eje_codigo, nombre, objetivo) values (22, 'EJE-02', 'Defensa del Consumidor', 'Crear canales rápidos de denuncia y mediación municipal.');
insert into programa (id, eje_codigo, nombre, objetivo) values (23, 'EJE-03', 'Infraestructura y Equipamiento Educativo', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (24, 'EJE-03', 'Educación para el Desarrollo', 'Diseñar currículas complementarias en valores, clima, género, cultura digital y comunidad.');
insert into programa (id, eje_codigo, nombre, objetivo) values (25, 'EJE-03', 'Educación Digital y Tecnologías para la Vida', 'Centros barriales con wifi, capacitación en apps, ciudadanía digital y plataformas.');
insert into programa (id, eje_codigo, nombre, objetivo) values (26, 'EJE-03', 'Innovación y Tecnología Aplicada', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (27, 'EJE-03', 'Ciudad Inteligente', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (28, 'EJE-03', 'Laboratorios Urbanos de Innovación Social', 'Espacios comunitarios para idear y testear ideas en salud, seguridad, cultura o reciclaje.');
insert into programa (id, eje_codigo, nombre, objetivo) values (29, 'EJE-04', 'Autonomía Económica de Mujeres', 'Red de capacitación, emprendimiento femenino, fondo semilla y espacios seguros de cuidado.');
insert into programa (id, eje_codigo, nombre, objetivo) values (30, 'EJE-04', 'Juventudes con Futuro', '10 centros juveniles distritales con enfoque en liderazgo, robótica, deporte y emprendimiento social.');
insert into programa (id, eje_codigo, nombre, objetivo) values (31, 'EJE-04', 'Empleo Productivo y Sostenible', 'Talleres de producción local (textil, alimentos, tecnología) con empleabilidad barrial.');
insert into programa (id, eje_codigo, nombre, objetivo) values (32, 'EJE-04', 'Empresas Públicas Eficientes', 'Auditoría técnica y rediseño de EMAVERDE, EMAVIAS, EPSAS y otras.');
insert into programa (id, eje_codigo, nombre, objetivo) values (33, 'EJE-04', 'Nuevas Empresas Mixtas', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (34, 'EJE-04', 'Mercados y Comercio Digno', 'Intervención integral en 30 mercados para infraestructura, digitalización y salud alimentaria.');
insert into programa (id, eje_codigo, nombre, objetivo) values (35, 'EJE-04', 'Planificación Productiva, Competitividad y Oportunidades Territoriales', 'Estudios y planes distritales para turismo, agroindustria, economía verde y manufactura.');
insert into programa (id, eje_codigo, nombre, objetivo) values (36, 'EJE-04', 'Ecosistema Municipal del Emprendimiento', 'Centro de formación, incubadora, ferias distritales, mentorías, plataforma digital de apoyo.');
insert into programa (id, eje_codigo, nombre, objetivo) values (37, 'EJE-04', 'Economía Social, Solidaria y Popular', 'Mapeo y fortalecimiento de más de 100 redes económicas barriales autogestionadas.');
insert into programa (id, eje_codigo, nombre, objetivo) values (38, 'EJE-05', 'Ciudad Longeva y Activa', 'Centros distritales de socialización, salud y participación activa.');
insert into programa (id, eje_codigo, nombre, objetivo) values (39, 'EJE-05', 'Ciudad Inclusiva con Discapacidad', 'Infraestructura accesible, bonos solidarios, cultura inclusiva.');
insert into programa (id, eje_codigo, nombre, objetivo) values (40, 'EJE-05', 'Infancia y Adolescencia Protegida', 'Brigadas escolares, ludotecas, unidades móviles de atención.');
insert into programa (id, eje_codigo, nombre, objetivo) values (41, 'EJE-05', 'Ciudad Segura para las Mujeres', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (42, 'EJE-05', 'Seguridad Ciudadana con Comunidad', 'Cámaras, luminarias, alarmas comunitarias, patrullaje conjunto.');
insert into programa (id, eje_codigo, nombre, objetivo) values (43, 'EJE-05', 'Redes de Cuidado Intergeneracional', 'Espacios de encuentro entre jóvenes, adultos mayores y cuidadores.');
insert into programa (id, eje_codigo, nombre, objetivo) values (44, 'EJE-05', 'Atención a Personas en Situación de Calle', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (45, 'EJE-05', 'Ciudad Protectora de Animales', 'Centro de atención veterinaria, esterilización, control y adopción.');
insert into programa (id, eje_codigo, nombre, objetivo) values (46, 'EJE-06', 'Culturas para la Vida', '15 centros culturales barriales con talleres, exposiciones y formación.');
insert into programa (id, eje_codigo, nombre, objetivo) values (47, 'EJE-06', 'Turismo de Altura', 'Circuito turístico-cultural con señalética, guías, eventos y patrimonio.');
insert into programa (id, eje_codigo, nombre, objetivo) values (48, 'EJE-06', 'Patrimonio para el Futuro', '100 cuadras históricas restauradas: fachadas, iluminación, mobiliario.');
insert into programa (id, eje_codigo, nombre, objetivo) values (49, 'EJE-06', 'Infraestructura Cultural y Recreativa', 'Teatro, parque Laikakota, La Bolita, infraestructura multifuncional.');
insert into programa (id, eje_codigo, nombre, objetivo) values (50, 'EJE-06', 'Economía Creativa y Naranja', 'Portal, ferias, créditos y formación para industrias culturales.');
insert into programa (id, eje_codigo, nombre, objetivo) values (51, 'EJE-06', 'Ciudad Vivencial Comunitaria y Laboratorios Culturales', 'Activaciones culturales, festivales, murales, teatro callejero por zonas.');
insert into programa (id, eje_codigo, nombre, objetivo) values (52, 'EJE-07', 'Planificación Territorial y Urbanismo Eficiente', 'Actualización y aplicación del Plan de Ordenamiento Territorial por distritos');
insert into programa (id, eje_codigo, nombre, objetivo) values (53, 'EJE-07', 'Habitat Digno y Vivienda Social', 'Construcción de 2.000 unidades bajo modelos de autoconstrucción asistida, cooperativas y alianzas');
insert into programa (id, eje_codigo, nombre, objetivo) values (54, 'EJE-07', 'Catastro Moderno y Justicia Urbana', 'Digitalización del 100% de predios urbanos y rurales con enfoque multipropósito');
insert into programa (id, eje_codigo, nombre, objetivo) values (55, 'EJE-07', 'Gestión del Suelo y Asentamientos Seguros', 'Regularización y contención territorial con servicios básicos en zonas priorizadas');
insert into programa (id, eje_codigo, nombre, objetivo) values (56, 'EJE-07', 'Prevención de Riesgos Urbanos', 'Formación, alarmas, simulacros, mapas participativos de riesgo.');
insert into programa (id, eje_codigo, nombre, objetivo) values (57, 'EJE-07', 'Sistema Inteligente de Monitoreo de Riesgos', 'Plataforma con sensores, cámaras, big data y equipos en campo.');
insert into programa (id, eje_codigo, nombre, objetivo) values (58, 'EJE-07', 'Equipamiento y Servicios Urbanos', 'Plataforma y plan maestro de equipamientos para garantizar cobertura por distrito');
insert into programa (id, eje_codigo, nombre, objetivo) values (59, 'EJE-07', 'Rehabilitación de Barrios Históricos', 'Renovación de 100 cuadras del centro histórico: fachadas, iluminación, mobiliario');
insert into programa (id, eje_codigo, nombre, objetivo) values (60, 'EJE-07', 'Barrios Comunitarios Autogestionados', 'Fondos concursables y capacitación técnica por zona urbana');
insert into programa (id, eje_codigo, nombre, objetivo) values (61, 'EJE-07', 'Regeneración y Mejora Integral de Barrios', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (62, 'EJE-07', 'Hábitat Verde y Urbanismo Ecosistémico', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (63, 'EJE-07', 'Red Distrital de Justicia y Mediación Barrial
“Derechos cerca de casa.”', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (64, 'EJE-08', 'Movilidad Urbana Sostenible', '120 km de rutas peatonales y ciclorrutas seguras, con infraestructura inclusiva.');
insert into programa (id, eje_codigo, nombre, objetivo) values (65, 'EJE-08', 'Sistema Integrado de Transporte Público', '5 líneas de teleférico + tren urbano central + billetera digital unificada');
insert into programa (id, eje_codigo, nombre, objetivo) values (66, 'EJE-08', 'Ordenamiento del Transporte Público Colectivo', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (67, 'EJE-08', 'Logística Urbana Inteligente', 'Adaptación de estaciones, aceras, señalética y vehículos accesibles');
insert into programa (id, eje_codigo, nombre, objetivo) values (68, 'EJE-08', 'Infraestructura Vial Estratégica', 'Intervención en 70 zonas críticas: señalización, carga-descarga, cámaras, mobiliario vial');
insert into programa (id, eje_codigo, nombre, objetivo) values (69, 'EJE-08', 'Parqueo y Control del Espacio Público Vial', '10 centros de parqueo vertical + fiscalización digital de uso de aceras y vías');
insert into programa (id, eje_codigo, nombre, objetivo) values (70, 'EJE-08', 'Control del Transporte Interciudad y Fronteras Urbanas', 'Estaciones de fiscalización conjunta La Paz – El Alto con sensores y registro');
insert into programa (id, eje_codigo, nombre, objetivo) values (71, 'EJE-08', 'Caminos Distritales y Rurales', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (72, 'EJE-08', 'Seguridad y Cultura Vial', 'Rehabilitación y mantenimiento comunitario de 500 km de caminos secundarios');
insert into programa (id, eje_codigo, nombre, objetivo) values (73, 'EJE-08', 'Movilidad Inclusiva y Accesibilidad Universal', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (74, 'EJE-08', 'Gestión Vehicular y Revisión Técnica Digital', 'Plataforma digital para revisión técnica, rastreo y pago en línea de impuestos');
insert into programa (id, eje_codigo, nombre, objetivo) values (75, 'EJE-08', 'Centralidades Urbanas', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (76, 'EJE-08', 'Cinvenios público - Privados para transpirte', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (77, 'EJE-08', 'Movilidad Activa', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (78, 'EJE-09', 'Gestión Ambiental Integral Urbana', 'Plataforma de licencias ambientales, monitoreo e indicadores.');
insert into programa (id, eje_codigo, nombre, objetivo) values (79, 'EJE-09', 'Áreas Verdes y Parques Urbanos', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (80, 'EJE-09', 'Reforestación Participativa y Conservación Urbana', 'Plantación y cuidado comunitario de 1 millón de árboles.');
insert into programa (id, eje_codigo, nombre, objetivo) values (81, 'EJE-09', 'Adaptación Climática Urbana y Gestión Hídrica', 'Microreservorios, jardines de lluvia, techos verdes, infiltración urbana.');
insert into programa (id, eje_codigo, nombre, objetivo) values (82, 'EJE-09', 'Energías Renovables y Eficiencia Energética', 'Paneles solares en 200 escuelas y edificios públicos.');
insert into programa (id, eje_codigo, nombre, objetivo) values (83, 'EJE-09', 'Gestión Integral de Residuos Sólidos', 'Optimizar recolección, crear rutas diferenciadas y nuevo centro de tratamiento.');
insert into programa (id, eje_codigo, nombre, objetivo) values (84, 'EJE-09', 'Economía Circular y Reciclaje Inclusivo', 'Plataforma de reciclaje con empresas, emprendedores y recicladores base.');
insert into programa (id, eje_codigo, nombre, objetivo) values (85, 'EJE-09', 'Centro Metropolitano de Residuos y Economía Verde', 'Infraestructura compartida entre La Paz, El Alto y municipios del eje.');
insert into programa (id, eje_codigo, nombre, objetivo) values (86, 'EJE-09', 'Agricultura Urbana y Soberanía Alimentaria', 'Crear 300 huertos escolares, barriales y en techos municipales.');
insert into programa (id, eje_codigo, nombre, objetivo) values (87, 'EJE-09', 'Educación y Cultura Ambiental Comunitaria', 'Activación de promotores ambientales en 100 unidades educativas.');
insert into programa (id, eje_codigo, nombre, objetivo) values (88, 'EJE-09', 'Biodiversidad Urbana y Protección de Fauna Silvestre', 'Espacios de protección y conectividad para aves, zorros, roedores silvestres.');
insert into programa (id, eje_codigo, nombre, objetivo) values (89, 'EJE-10', 'Planes Metropolitanos de Desarrollo Urbano y Territorial', 'Hoja de ruta compartida con visión territorial, ambiental y económica.');
insert into programa (id, eje_codigo, nombre, objetivo) values (90, 'EJE-10', 'Mancomunidades Productivas y Ambientales', 'Apoyo a ferias, agroindustria, agricultura ecológica, con enfoque metropolitano.');
insert into programa (id, eje_codigo, nombre, objetivo) values (91, 'EJE-10', 'Centralidades Metropolitanas', 'Crear polos de cultura, comercio y movilidad en límites con El Alto, Achocalla.');
insert into programa (id, eje_codigo, nombre, objetivo) values (92, 'EJE-10', 'Cultura e Identidad Metropolitana', 'Activación de expresiones culturales mixtas entre La Paz y El Alto.');
insert into programa (id, eje_codigo, nombre, objetivo) values (93, 'EJE-10', 'Gobernanza Metropolitana y Coordinación Intermunicipal', 'Crear una instancia formal de coordinación con competencias delegadas.');
insert into programa (id, eje_codigo, nombre, objetivo) values (94, 'EJE-10', 'Gestión Metropolitana de Servicios Básicos y Ambientales', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (95, 'EJE-10', 'Integración Metropolitana de Transporte y Logística', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (96, 'EJE-10', 'Centro Metropolitano de Soluciones Urbanas – CEMSU', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (97, 'EJE-10', 'Red Campo-Ciudad', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (98, 'EJE-10', 'Red de Apoyo municipal', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (99, 'EJE-01', 'Fortalecimiento Institucional y Gestión Interna (paraguas CMI)', NULL);
insert into programa (id, eje_codigo, nombre, objetivo) values (100, 'EJE-05', 'Seguridad Alimentaria', NULL);
select setval('programa_id_seq', (select max(id) from programa));

-- 386 proyectos
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (1, 'Pacto Urbano Ciudad Humana: Carta de principios firmada y socializada.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (1, 'Carta Urbana de La Paz 2050', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (1, 'Carta Urbana de La Paz', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (1, 'Observatorio de Gobernanza Urbana', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (2, 'Portal de Normas Urbanas Vivas.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (2, 'Paragua Normativo para el Desarrollo', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (2, 'Banco de Convenios Urbanos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (2, 'Reforma del Código Municipal Urbano', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (3, 'La Paz Planifica con la Gente.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (3, 'Observatorio Urbano Digital', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (3, 'POT por Distritos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (3, 'Plataforma de Planificación Digital', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (4, 'Archivo Digital Abierto de la Ciudad.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (4, 'Gobierno Abierto en Territorio.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (4, 'Nueva Estructura Municipal Territorizada', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (4, 'Rediseño Organizativo GAMLP', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (4, 'Indicadores por distrito', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (5, 'La Paz Gana con Tu Aporte.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (5, 'Contribuyente Humano: Reconocimiento ciudadano.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (5, 'Fondos Ciudadanos para Proyectos Locales.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (5, 'Ciudadanía Fiscal Responsable', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (5, 'Aplicativo de Pago Móvil Municipal', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (6, 'Presupuesto Participativo Vecinal.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (6, 'POA Visual Ciudadano', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (6, 'Ranking por ejecución y calidad de obras - 10 premios de 100.000 en obras', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (6, 'POA Visual Participativo', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (6, 'Ranking Distrital de Cumplimiento', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (7, 'Transparencia en 1 Click.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (7, 'Confía La Paz', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (8, 'Red de Veeduría Ciudad Humana.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (8, 'Escuela de Contralores Sociales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (9, 'Ciudad con Ojos Abiertos.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (9, 'Evalúa Tu Obra', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (10, 'Presupuesta Tu Barrio.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (10, 'La Paz Decide', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (11, 'Banco Social de la Ciudad.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (11, 'Ciudad Humana Invierte', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (11, 'Fondo Fiduciario Ciudad Humana (FFCH)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (11, 'Unidad Técnica de Proyectos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (12, 'Alianzas por la Vida Urbana.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (12, 'Aliados por la Ciudad Humana', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (12, 'Ventanilla de APP para servicios urbanos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (13, 'Mapa Integrado de Políticas de Ciudad.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (13, 'La Paz Merece Más', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (13, 'La Paz Merece', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (13, 'Convenios con BID/CAF/ONU', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (13, 'Hábitat', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (14, 'Municipio Inteligente y Humano.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (14, 'Plataforma Ciudad Digital', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (14, 'Ciudad Digital Participativa', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (14, 'Registro Único del Ciudadano', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (15, 'Clínicas de Vida: Salud donde vives.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (15, 'Eje I (Financiamiento), Eje IV (Empleo), Eje IX (Ambiente saludable)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (15, 'Centros Distritales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (15, 'Red de Salud Familiar', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (16, 'Red de Salud Inteligente de Barrio.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (16, 'Eje III (Innovación), Eje VIII (Movilidad sanitaria), Eje IX (Clima)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (16, 'Laboratorio de Vigilancia Epidemiológica', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (16, 'App de Salud Preventiva', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (17, 'La Paz Te Escucha: Espacios de escucha, contención y acompañamiento.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (17, 'Eje V (Redes de cuidado), Eje VI (Cultura), Eje IV (Juventudes)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (17, 'Centros Distritales de Salud Mental', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (17, 'Brigadas Escolares de Apoyo Psicológico', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (18, 'Barrio Activo: Circuitos deportivos barriales.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (18, 'Eje III (Educación), Eje IV (Juventud), Eje V (Prevención)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (18, 'Eje VII (Espacio público), Eje V (Seguridad), Eje IV (Juventud)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (18, 'Escuelas Deportivas Barriales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (18, 'Deporte con Propósito (Disciplina + valores)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (19, 'Eje VI (Cultura), Eje IV (Juventud), Eje X (Metropolitano)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (19, 'Centro de Alto Rendimiento Paceño', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (19, 'Becas para Atletas Urbanos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (20, 'Aliméntate Bien, Vive Mejor: Etiqueta municipal de alimentos seguros.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (20, 'Eje IV (Mercados), Eje I (Participación), Eje VII (Control urbano)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (20, 'Reservorios Urbanos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (20, 'Red de Recolección Pluvial', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (21, 'Agua para la Vida: Redes solidarias y tanques comunitarios.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (21, 'Eje IX (Adaptación Climática), Eje X (Gobernanza Metropolitana), Eje I (POA resiliente)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (21, 'Laboratorio Municipal de Alimentos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (21, 'Etiquetado Municipal para Comer Bien', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (22, 'Alerta Justa: App para control comunitario de abusos.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (22, 'Eje I (Digitalización), Eje IV (Economía local), Eje V (Justicia comunitaria)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (22, 'Ventanilla del Consumidor Municipal', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (22, 'Brigadas de Control de Abusos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (23, 'Eje II (Salud Escolar), Eje I (Financiamiento), Eje VII (Equipamiento)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (23, 'Plan de Rehabilitación Escolar', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (23, 'Mantenimiento con Brigadas Ciudadanas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (24, 'Escuela de Ciudadanía Viva y Aprendizaje Colectivo.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (24, 'Eje IV (Juventudes), Eje IX (Clima), Eje V (Convivencia)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (24, 'Programa “Aprender para la Vida”', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (24, 'Itinerarios Educativos por Talento', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (25, 'Ciudad Crea: Laboratorios de Innovación Ciudadana.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (25, 'Eje I (Transformación digital), Eje IV (Empleo), Eje VIII (Conectividad)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (25, 'Conectividad Total Distrital', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (25, 'Centros de Inclusión Digital', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (26, 'Eje IX (Economía Circular), Eje VIII (Movilidad), Eje VI (Turismo)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (26, 'Hackatones Urbanas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (26, 'Desafíos Ciudadanos de Soluciones', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (27, 'Eje I (Digitalización), Eje VII (Ordenamiento), Eje VIII (Control vehicular)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (27, 'Red de Datos Urbanos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (27, 'Paneles de Gestión en Tiempo Real', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (28, 'Ciudad Humana Innova: Feria anual de soluciones urbanas.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (28, 'Eje VI (Cultura), Eje II (Salud mental), Eje IV (Juventudes)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (28, 'Proyectos pilotos vecinales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (28, 'Fondos de Innovación Participativa', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (29, 'Fuerza Mujer: Fondo y Red de Apoyo Económico Local.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (29, 'Eje V (Igualdad), Eje III (Educación Digital)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (29, 'Fuerza Mujer (fondo semilla + cuidados)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (29, 'Escuelas Productivas para Mujeres', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (30, 'Jóvenes que Transforman: Escuelas de Liderazgo y Emprendimiento.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (30, 'Pasantes para el desarrollo "Mi primer empleo al servico de La Paz"', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (30, 'Eje III (Tecnología), Eje VI (Cultura), Eje II (Salud Mental)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (30, 'Líderes del Bicentenario', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (30, 'Centros de Formación y Liderazgo Juvenil', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (31, 'Empleo con Rostro Humano: Ferias y Bolsas de Trabajo Comunitarias.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (31, 'Eje VII (Equipamiento), Eje IX (Reciclaje)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (31, 'Fábricas Urbanas Barriales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (31, 'Escuelas Taller Municipales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (32, 'Empresa Ciudad Humana: Servicios que transforman.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (32, 'Eje I (Transparencia), Eje IX (Agua)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (32, 'Auditoría y Reingeniería de EMAVERDE/EMAVIAS', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (32, 'Centro de Control de Empresas Municipales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (33, 'Eje IX (Residuos), Eje II (Salud), Eje VIII (Logística)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (33, 'Empresa de Alimentos Populares', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (33, 'Empresa Municipal de Residuos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (34, 'Mi Mercado, Mi Comunidad: Red de Mercados Dignos.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (34, 'Eje VII (Equipamiento), Eje II (Salud), Eje VI (Cultura)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (34, 'Mercados Ciudad Humana', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (34, 'Red de Comercio Digital', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (35, 'Distritos con Identidad Productiva.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (35, 'Eje IX (Vocación Rural), Eje VI (Turismo), Eje VII (Ordenamiento)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (35, 'Distritos Productivos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (35, 'Feria Metropolitana de Vocaciones', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (36, 'Impulsa Tu Sueño: Aceleradora de Emprendimientos Sociales.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (36, 'Eje III (Innovación), Eje IX (Circular), Eje X (Metropolitano)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (36, 'Instituto Municipal de Emprendimiento', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (36, 'Ferias + Incubadoras', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (37, 'Red Solidaria La Paz: Plataforma de Consumo Justo.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (37, 'Centros de Oportunidades Ciudadanas.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (37, 'Tu Barrio tu cooperativa', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (37, 'Eje II (Salud), Eje IX (Reciclaje), Eje V (Adultos Mayores)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (37, 'Redes de Trueque y Ferias Solidarias', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (37, 'Cooperativas Barriales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (38, 'Red de Centros Vida: Clubes del Buen Vivir para Adultos Mayores.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (38, 'Eje II (Salud), Eje IX (Verde)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (38, 'Casas Distritales del Adulto Mayor', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (38, 'Clubes de Movimiento y Memoria', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (39, 'Ruta Inclusiva: Calles, plazas y servicios para todos.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (39, 'Eje VII (Infraestructura), Eje III (Innovación)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (39, 'Red de Accesibilidad Territorial', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (39, 'Banco de Ayudas Técnicas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (40, 'Voces Pequeñas, Decisiones Grandes: Participación Infantil Barrial.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (40, 'Eje II (Salud mental), Eje VI (Cultura)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (40, 'Escuelas de Familias', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (40, 'Casas de Protección Integral', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (41, 'Ciudad de La Mujer', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (41, 'Eje IX (Salud Ambiental), Eje VI (Cultura Comunitaria)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (41, 'Centro de Bienestar Animal', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (41, 'Brigadas de Protección de Mascotas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (42, 'Barrios Seguros desde la Comunidad: Alarmas con vecinos y cultura de paz.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (42, 'Eje IX (Adaptación Climática), Eje I (Gestión de Riesgo)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (42, 'Intervención de 180 Taludes', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (42, 'Forestación de Quebradas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (43, 'Tejiendo Cuidados: Espacios de encuentro entre generaciones.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (43, 'Eje VII (Catastro), Eje X (Mancomunidad)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (43, 'Programa de Alquiler Social', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (43, 'Mejoramiento de Viviendas Populares', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (44, 'Eje I (Participación), Eje III (Educación Legal)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (44, 'Casas Distritales de Justicia', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (44, 'Mediación Comunitaria', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (45, 'Patitas Seguras: Veterinarias comunitarias y adopción responsable.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (45, 'Eje I (APPs), Eje VIII (Iluminación)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (45, 'Redes Vecinales Inteligentes', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (45, 'Iluminación Pública Participativa', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (46, 'Red de Cultura Viva Barrial.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (46, 'Eje II (Salud mental), Eje III (Educación), Eje X (Metropolitano)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (46, 'Festival de la Paz', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (46, 'Escuelas Municipales de Arte', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (47, 'La Paz Se Vive: Rutas humanas y patrimoniales.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (47, 'Eje IV (Economía), Eje VII (Centralidades), Eje VIII (Movilidad)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (47, 'Vía Balcón Turística', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (47, 'Parque Urbano Central + Mercado Patrimonial', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (48, 'Memoria Viva: Adopta tu Patrimonio.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (48, 'Eje I (Planificación), Eje VII (Barrios), Eje VIII (Espacio público)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (48, 'Registro Patrimonial + Intervención de Barrios', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (48, 'Custodia Patrimonial Comunitaria', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (49, 'Escenarios Abiertos: Cultura al aire libre.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (49, 'Eje II (Salud), Eje IV (Juventud), Eje IX (Verde)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (49, 'Renovación del Teatro al Aire Libre', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (49, 'Centros Culturales Barriales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (50, 'Fondo Cultural Ciudad Humana.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (50, 'Eje IV (Emprendimiento), Eje III (Innovación)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (50, 'Red de Industrias Culturales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (50, 'Mercado Digital para Creadores', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (51, 'Mercados con Identidad: Cultura en la Canasta.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (51, 'Caseritas de la Vida', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (51, 'Barrios Culturales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (51, 'La noche Blanca', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (51, 'Eje V (Identidad), Eje X (Mancomunidad), Eje IX (Espacios verdes)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (51, 'Laboratorios de Cultura Viva', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (51, 'Escuela de Memoria Barrial', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (52, 'Mapa Vivo de la Ciudad: Planificación desde la comunidad.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (52, 'Eje I (Normativa), Eje IX (Clima)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (52, 'Plan de Ordenamiento Territorial', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (52, 'Planes Distritales Territoriales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (53, 'Techo con Sentido: Vivienda para la vida.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (53, 'Eje V (Discapacidad, Adulto Mayor), Eje I', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (53, 'Programa de Rehabilitación de Barrios Populares', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (53, 'Alquiler Social', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (54, 'Tu Terreno Cuenta: Regularización con justicia social.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (54, 'Eje I (Tributación), Eje III (Tecnología)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (54, 'Catastro Digital Territorial', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (54, 'Mapeo de Infraestructura y Servicios', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (55, 'Barrios Reconocidos, Barrios Cuidados.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (55, 'Eje IX (Riesgos), Eje II (Salud)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (55, 'Programa de Regularización con Seguridad', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (55, 'Protección de Áreas de Riesgo', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (56, 'Ciudad Alerta: Simulacros y preparación comunitaria ante riesgos.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (56, 'Eje III (Tecnología), Eje I (Planificación)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (56, 'Sensores + Centro de Monitoreo', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (56, 'Aplicación de Alerta Temprana', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (57, 'Red de Vigilantes del Territorio.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (57, 'Eje II (Salud Mental), Eje IV (Economía Solidaria)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (57, 'Casas Distritales de Cuidados', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (57, 'Voluntariado Solidario', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (58, 'Equipamos La Paz: Infraestructura con propósito humano.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (58, 'Eje II (Salud), Eje VIII (Movilidad)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (58, 'Infraestructura de Centros de Salud y Educación', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (58, 'Equipamiento de Barrios Periurbanos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (59, 'Barrios con Historia Viva: Rehabilitación urbana participativa.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (59, 'Eje VI (Cultura), Eje X (Turismo)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (59, 'Intervención de Calle Jaén y alrededores', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (59, 'Mejoras en zonas patrimoniales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (60, 'Hábitat Humano: Vivienda, comunidad y naturaleza.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (60, 'Eje I (Participación), Eje IV', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (60, 'Planes Participativos de Mejoramiento', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (60, 'Fondos Concursables Vecinales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (61, 'Eje IX (Espacio público), Eje V', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (61, 'Intervenciones integrales: iluminación, escaleras, calles', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (62, 'Eje IX (Ambiente), Eje II', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (62, 'Parques Barriales Resilientes', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (62, 'Infraestructura Verde en barrios', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (63, 'Eje I, II, IV, VI, VII', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (63, 'Calles Seguras para Ellas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (63, 'Alertas Comunitarias contra la Violencia', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (64, 'Muévete La Paz: Red multimodal sostenible.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (64, 'Eje II (Salud), Eje IX (Clima), Eje V (Discapacidad)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (64, 'Caminabilidad Distrital', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (64, 'Red de Ciclorrutas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (65, 'Tarjeta Ciudad Humana: Transporte unificado y social.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (65, 'Eje I (Financiamiento), Eje X (Metropolitano), Eje VI (Cultura)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (65, 'Teleféricos Movilivida', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (65, 'Tren Urbano Central', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (66, 'Eje V (Seguridad), Eje IV (Empleo), Eje I (Gestión)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (66, 'Rutas Integradas Inteligentes', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (66, 'Formalización del Transporte Popular', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (67, 'Ciudad que Se Mueve: Red de Distribución Urbana Sostenible.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (67, 'Eje VII (Vialidad), Eje IV (Comercio), Eje III (Tecnología)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (67, 'Paradas Seguras y Digitalizadas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (67, 'Semáforos y Sensores de Flujo Vehicular', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (68, 'La Vía es Nuestra: Calles completas para todas las personas.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (68, 'Eje VII (Equipamiento), Eje IX (Territorio), Eje X (Integración)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (68, 'Vías Distritales de Conexión', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (68, 'Intervenciones en Cuellos de Botella', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (69, 'Parqueo Inteligente y Vecinal.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (69, 'Eje I (Ordenamiento), Eje VI (Convivencia), Eje VII (Catastro)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (69, 'Red de Parqueos Municipales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (69, 'Regulación del Espacio Público', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (70, 'Terminal Inteligente Metropolitana.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (70, 'Eje X (Gobernanza), Eje I (Gestión), Eje IV (Logística)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (70, 'Terminales Metropolitanas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (70, 'Puntos de Control y Fiscalización', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (71, 'Guardianes de la Movilidad: Patrullas cívicas con formación ciudadana.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (71, 'Eje IX (Productivo rural), Eje VII (Vivienda), Eje II (Emergencias)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (71, 'Mantenimiento Preventivo Distrital', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (71, 'Caminos Rurales de Conexión', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (72, 'Escuela de Movilidad Humana: Aprender para convivir.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (72, 'Eje V (Niñez, Adulto Mayor), Eje II (Salud Mental)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (72, 'Educación Vial Escolar', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (72, 'Infraestructura Segura', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (73, 'Eje V (Discapacidad), Eje IX (Ciudad humana), Eje I (Participación)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (73, 'Transporte Accesible', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (73, 'Intervenciones de Rampa y Guías Podotáctiles', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (74, 'Tu Auto en la Ciudad: Registro digital ciudadano.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (74, 'Rodamos Seguros: Centros móviles de inspección.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (74, 'Eje I (Digitalización), Eje III (Innovación), Eje V (Seguridad)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (74, 'Plataforma Municipal de Vehículos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (74, 'Revisión Técnica Automatizada', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (75, 'Mi Distrito, Mi Centro: Centralidades con Identidad.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (75, 'Recuperemos la Calle: Espacios públicos para el encuentro.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (76, 'Conduce con Propósito: Alianzas para movilidad humana.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (77, 'Pedalea La Paz: Ciclorutas y bicibuses escolares.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (78, 'Guardianes Verdes: Brigadas comunitarias de reforestación.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (78, 'Eje I (Transparencia), Eje VII (Catastro)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (78, 'Marco Normativo Ambiental', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (78, 'Sistema de Licencias y Fiscalización', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (79, 'Eje VI (Cultura), Eje V (Infancia), Eje VII (Ordenamiento)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (79, 'Parques Renovados con Comunidades', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (79, 'Mantenimiento Participativo', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (80, 'Respira La Paz: Campaña ciudadana de reforestación.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (80, 'Eje V (Riesgos), Eje II (Salud), Eje X (Gobernanza)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (80, 'Red de Reforestación Barrial', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (80, 'Jardines Escolares Comunitarios', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (81, 'Escudos Verdes: Estrategia climática comunitaria.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (81, 'Eje II (Agua segura), Eje V (Gestión de Riesgos)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (81, 'Infraestructura de Drenaje Verde', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (81, 'Reservorios de Agua Urbana', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (82, 'Ciudad Solar: Energía para la vida.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (82, 'Eje III (Educación), Eje I (Gestión municipal)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (82, 'Techos Solares Municipales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (82, 'Alumbrado Solar Distrital', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (83, 'Basura Cero: Comunidad que separa y reduce.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (83, 'Eje IV (Empresas), Eje V (Salud), Eje VII (Logística)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (83, 'Recolección Segregada', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (83, 'Nueva Planta de Tratamiento', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (84, 'Circular La Paz: Laboratorio de economía regenerativa.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (84, 'La Paz Recicla con Dignidad: Red de recicladores y educación urbana.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (84, 'Eje IV (Empleo), Eje III (Innovación), Eje VI (Eventos)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (84, 'Centros de Acopio con Recicladores', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (84, 'Ferias de Economía Circular', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (85, 'Parque Ecoindustrial del Reciclaje.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (85, 'Eje X (Metropolitano), Eje IV (Empleo Verde)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (85, 'Plataforma de Gestión Integral Metropol.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (85, 'Compostaje y reciclaje industrial', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (86, 'Sembrando Futuro: Red de Huertas Ciudadanas.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (86, 'Eje II (Salud), Eje IV (Mujeres), Eje VII (Espacio urbano)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (86, 'Huertos Escolares y Vecinales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (86, 'Circuitos Cortos Agroecológicos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (87, 'Corredores Verdes Urbanos.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (87, 'Eje III (Educación), Eje V (Juventud), Eje VI (Cultura)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (87, 'Escuelas Ambientales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (87, 'Brigadas Climáticas Barriales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (88, 'De la Tierra al Plato: Circuitos cortos y mercados saludables.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (88, 'Eje X (Periurbano), Eje V (Protección animal)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (88, 'Reservas Urbanas + Bioindicadores', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (88, 'Refugios y Santuarios', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (89, 'Gran La Paz Humana: Foro de Alcaldías y Ciudadanía Metropolitana.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (89, 'Eje VII (Ordenamiento), Eje I (Gobernanza), Eje IX (Residuos)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (89, 'POT Metropolitano Intermunicipal', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (89, 'Estrategia Metropolitana 2050', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (90, 'Regiones que Producen Vida: Ferias mancomunadas y clústeres regionales.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (90, 'Eje IX (Agricultura), Eje IV (Empleo), Eje VI (Cultura)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (90, 'Circuitos Productivos Regionales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (90, 'Gestión de Cuencas Compartidas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (91, 'Ej. Estación de >Faro Murillo', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (91, 'Eje IV (Economía), Eje VIII (Movilidad), Eje VI (Turismo)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (91, 'Distritos Binacionales La Paz–El Alto', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (91, 'Nodos de Desarrollo Urbano', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (92, 'Ruta Metropolitana de las Culturas Vivas.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (92, 'Eje VI (Cultura), Eje V (Juventud)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (92, 'Encuentro Cultural Metropolitano', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (92, 'Escuela de Identidad Metropolitana', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (93, 'Mesa Metropolitana de Ciudadanía y Territorio.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (93, 'Eje I (Gestión Municipal), Eje IX (Servicios Ambientales)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (93, 'Consejo de Alcaldes Metropolitanos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (93, 'Agenda Legislativa Intermunicipal', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (94, 'Eje IX (Residuos), Eje II (Salud), Eje VII (Equipamiento)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (94, 'Convenio Residuos y Agua', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (94, 'Sistemas Integrados de Alumbrado y Recolección', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (95, 'Eje VIII (Movilidad), Eje I (Digitalización), Eje IV (Logística)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (95, 'Red Integrada de Transporte Urbano', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (95, 'Tarifa Única Metropolitana', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (96, 'Eje III (Innovación), Eje I (Planificación), Eje IX (Adaptación climática)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (96, 'Plataforma Técnica Metropolitana', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (96, 'Centro de Datos Urbanos Compartidos', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, '1. Mercados Integradores Territoriales (MIT)', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, 'Mercados urbanos semi-mayoristas o de consumo directo, gestionados junto a comunidades productoras, con trazabilidad, logística compartida y precios justos.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, '2. App Campo-Ciudad', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, 'Una aplicación digital de comercio justo, logística compartida y consumo responsable que conecte productores rurales con familias urbanas, restaurantes y hoteles.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, '3. Bancos de Insumos y Semillas Rurales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, 'Centros urbanos que provean, en alianza con gobiernos locales, insumos, asistencia técnica, crédito rotativo y tecnología al sector rural.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, '4. Escuelas Urbanas de Saberes Rurales', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, 'Espacios en la ciudad donde se enseñan oficios, técnicas ancestrales, producción agroecológica, cocina rural y cultura originaria. Fomentan el orgullo rural y el aprendizaje mutuo.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, '5. Rutas del Origen', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, 'Circuitos turísticos y educativos entre barrios urbanos y comunidades rurales que promuevan identidad, turismo responsable y comercio directo.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, '6. Centros de Acopio con Frío y Valor Agregado', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, 'Ubicados en el periurbano, permitirían industrializar productos rurales para generar empleo y aumentar el valor de exportación.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, '7. Sistema de Transferencias Verdes Urbanas', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (97, 'Una parte del presupuesto municipal o distrital que se destine a la protección de cuencas, reforestación, agricultura sostenible o soberanía alimentaria en zonas rurales.', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (98, 'Cooperativa de asesoramiento municipal', 'general', NULL, NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (99, 'La Paz Comunica', 'paraguas', 'Comunicación estratégica, prensa y marca ciudad: difundir la gestión y posicionar La Paz.', NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (99, 'Casa Ordenada', 'paraguas', 'Gestión interna, mantenimiento, equipamiento y destrabe de trámites operativos de la Alcaldía.', NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (99, 'Servidores que Cuidan', 'paraguas', 'Bienestar y condiciones laborales del personal municipal (obreros, servicios).', NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (99, 'Finanzas Sanas', 'paraguas', 'Sostenibilidad financiera y presupuestaria: recaudación, tarifas y saneamiento del gasto.', NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (99, 'Control y Cuentas Claras', 'paraguas', 'Auditoría interna, fiscalización y saneamiento de activos y contrataciones.', NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (99, 'Agenda Viva de la Ciudad', 'paraguas', 'Protocolo, relacionamiento institucional, agenda y cultura cívica.', NULL, NULL, NULL);
insert into proyecto (programa_id, nombre, tipo, objetivo, meta, indicador, resultado_2030) values (100, 'Alimentación Solidaria', 'general', 'Programa de alimentación a poblaciones vulnerables (personas en situación de calle, adultos mayores, bajos recursos).', NULL, NULL, NULL);

