-- 0006 · encaje de los 32 sin código (schema cmi). Generado; no editar a mano.
set search_path to cmi, public;

-- actividad genérica por proyecto (si no existe ya)
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Auditoría y Reingeniería de EMAVERDE/EMAVIAS' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Barrios Seguros desde la Comunidad: Alarmas con vecinos y cultura de paz.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Caseritas de la Vida' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Circular La Paz: Laboratorio de economía regenerativa.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Ciudad Alerta: Simulacros y preparación comunitaria ante riesgos.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Ciudad con Ojos Abiertos.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Clínicas de Vida: Salud donde vives.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Control y Cuentas Claras' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Festival de la Paz' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Finanzas Sanas' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='La Paz Se Vive: Rutas humanas y patrimoniales.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='La Vía es Nuestra: Calles completas para todas las personas.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Memoria Viva: Adopta tu Patrimonio.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Muévete La Paz: Red multimodal sostenible.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Parques Renovados con Comunidades' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Red de Centros Vida: Clubes del Buen Vivir para Adultos Mayores.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Red de Vigilantes del Territorio.' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');
insert into actividad (proyecto_id, nombre) select pr.id,'General (compromisos)' from proyecto pr where pr.nombre='Servidores que Cuidan' and not exists (select 1 from actividad a where a.proyecto_id=pr.id and a.nombre='General (compromisos)');

-- asignar código + enganchar cada una de las 32 (match por título, solo las sin código)
update tarea set codigo='C270', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Barrios Seguros desde la Comunidad: Alarmas con vecinos y cultura de paz.' and a.nombre='General (compromisos)' limit 1) where titulo='Atender la problemática de seguridad ciudadana nocturna (night clubs y zona roja) en el sector del Puente de las Américas' and (codigo is null or codigo='');
update tarea set codigo='C271', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Red de Centros Vida: Clubes del Buen Vivir para Adultos Mayores.' and a.nombre='General (compromisos)' limit 1) where titulo='Brindar apoyo social a la persona adulta mayor reubicada de la calle Nieves–Linares' and (codigo is null or codigo='');
update tarea set codigo='C272', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Servidores que Cuidan' and a.nombre='General (compromisos)' limit 1) where titulo='Completar la entrega de equipamiento de protección personal a los trabajadores' and (codigo is null or codigo='');
update tarea set codigo='C273', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Clínicas de Vida: Salud donde vives.' and a.nombre='General (compromisos)' limit 1) where titulo='Concluir la construcción del Hospital San Antonio pese al retraso frente al plazo comprometido' and (codigo is null or codigo='');
update tarea set codigo='C274', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='La Vía es Nuestra: Calles completas para todas las personas.' and a.nombre='General (compromisos)' limit 1) where titulo='Conformar la mesa técnica y definir el plan de intervención integral de la Avenida del Poeta' and (codigo is null or codigo='');
update tarea set codigo='C275', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Festival de la Paz' and a.nombre='General (compromisos)' limit 1) where titulo='Contratar baños públicos para la verbena paceña' and (codigo is null or codigo='');
update tarea set codigo='C276', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Festival de la Paz' and a.nombre='General (compromisos)' limit 1) where titulo='Coordinar el despliegue de seguridad para la verbena paceña' and (codigo is null or codigo='');
update tarea set codigo='C277', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Clínicas de Vida: Salud donde vives.' and a.nombre='General (compromisos)' limit 1) where titulo='Decidir sobre la inclusión del generador de oxígeno (Bs 2.000.000) en el equipamiento del Hospital San Antonio' and (codigo is null or codigo='');
update tarea set codigo='C278', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='La Vía es Nuestra: Calles completas para todas las personas.' and a.nombre='General (compromisos)' limit 1) where titulo='Ejecutar el plan de bacheo intensivo en toda la ciudad' and (codigo is null or codigo='');
update tarea set codigo='C279', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='La Vía es Nuestra: Calles completas para todas las personas.' and a.nombre='General (compromisos)' limit 1) where titulo='Ejecutar el programa integral de mejoramiento definitivo de vías fundamentales' and (codigo is null or codigo='');
update tarea set codigo='C280', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='La Vía es Nuestra: Calles completas para todas las personas.' and a.nombre='General (compromisos)' limit 1) where titulo='Ejecutar la demolición controlada y restitución de la vía en la calle Nieves–Linares' and (codigo is null or codigo='');
update tarea set codigo='C281', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Control y Cuentas Claras' and a.nombre='General (compromisos)' limit 1) where titulo='Emitir informe oficial sobre las modificaciones contractuales del Hospital San Antonio y determinar responsables de los cambios' and (codigo is null or codigo='');
update tarea set codigo='C282', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Ciudad Alerta: Simulacros y preparación comunitaria ante riesgos.' and a.nombre='General (compromisos)' limit 1) where titulo='Evaluar y declarar la alerta roja municipal ante el fenómeno de El Niño' and (codigo is null or codigo='');
update tarea set codigo='C283', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Ciudad con Ojos Abiertos.' and a.nombre='General (compromisos)' limit 1) where titulo='Fiscalizar la ejecución del POA 2025 entregado por la dirigencia vecinal' and (codigo is null or codigo='');
update tarea set codigo='C284', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Clínicas de Vida: Salud donde vives.' and a.nombre='General (compromisos)' limit 1) where titulo='Gestionar el proceso de contratación y presupuesto para el equipamiento del Hospital San Antonio' and (codigo is null or codigo='');
update tarea set codigo='C285', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Parques Renovados con Comunidades' and a.nombre='General (compromisos)' limit 1) where titulo='Habilitar el Jardín Botánico como parque-escuela' and (codigo is null or codigo='');
update tarea set codigo='C286', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Memoria Viva: Adopta tu Patrimonio.' and a.nombre='General (compromisos)' limit 1) where titulo='Instalar una valla de protección para el muro patrimonial de la iglesia de San Francisco' and (codigo is null or codigo='');
update tarea set codigo='C287', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='La Vía es Nuestra: Calles completas para todas las personas.' and a.nombre='General (compromisos)' limit 1) where titulo='Mejorar la iluminación de la ruta del Gran Poder para la festividad' and (codigo is null or codigo='');
update tarea set codigo='C288', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Finanzas Sanas' and a.nombre='General (compromisos)' limit 1) where titulo='Pagar los sueldos atrasados a los trabajadores de EMAVERDE' and (codigo is null or codigo='');
update tarea set codigo='C289', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='La Paz Se Vive: Rutas humanas y patrimoniales.' and a.nombre='General (compromisos)' limit 1) where titulo='Presentar la estimación del impacto económico de la verbena paceña' and (codigo is null or codigo='');
update tarea set codigo='C290', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Red de Vigilantes del Territorio.' and a.nombre='General (compromisos)' limit 1) where titulo='Programar inspección técnica al muro de contención de Seguencoma' and (codigo is null or codigo='');
update tarea set codigo='C291', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Caseritas de la Vida' and a.nombre='General (compromisos)' limit 1) where titulo='Programar reuniones con las caseras para distribuir espacios durante la verbena' and (codigo is null or codigo='');
update tarea set codigo='C292', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Servidores que Cuidan' and a.nombre='General (compromisos)' limit 1) where titulo='Realizar la evaluación de desempeño del personal del Jardín Botánico' and (codigo is null or codigo='');
update tarea set codigo='C293', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Circular La Paz: Laboratorio de economía regenerativa.' and a.nombre='General (compromisos)' limit 1) where titulo='Recoger y reciclar los troncos podados y caídos del Jardín Botánico' and (codigo is null or codigo='');
update tarea set codigo='C294', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Parques Renovados con Comunidades' and a.nombre='General (compromisos)' limit 1) where titulo='Rediseñar las estructuras del Jardín Botánico con criterio arquitectónico' and (codigo is null or codigo='');
update tarea set codigo='C295', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Parques Renovados con Comunidades' and a.nombre='General (compromisos)' limit 1) where titulo='Reforzar la seguridad perimetral del Jardín Botánico' and (codigo is null or codigo='');
update tarea set codigo='C296', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Muévete La Paz: Red multimodal sostenible.' and a.nombre='General (compromisos)' limit 1) where titulo='Registrar el proyecto de gradas eléctricas para San Antonio' and (codigo is null or codigo='');
update tarea set codigo='C297', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Control y Cuentas Claras' and a.nombre='General (compromisos)' limit 1) where titulo='Remitir a auditoría la falta de pago del servicio de agua de la gestión anterior' and (codigo is null or codigo='');
update tarea set codigo='C298', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Finanzas Sanas' and a.nombre='General (compromisos)' limit 1) where titulo='Restituir el agua del Jardín Botánico y los parques (deuda con EPSAS)' and (codigo is null or codigo='');
update tarea set codigo='C299', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Clínicas de Vida: Salud donde vives.' and a.nombre='General (compromisos)' limit 1) where titulo='Revisar la normativa de colores hospitalarios y revertir los colores políticos aplicados en el Hospital San Antonio' and (codigo is null or codigo='');
update tarea set codigo='C300', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Clínicas de Vida: Salud donde vives.' and a.nombre='General (compromisos)' limit 1) where titulo='Revisar y corregir el diseño de flujos hospitalarios del Hospital San Antonio' and (codigo is null or codigo='');
update tarea set codigo='C301', actividad_id=(select a.id from actividad a join proyecto pr on pr.id=a.proyecto_id where pr.nombre='Auditoría y Reingeniería de EMAVERDE/EMAVIAS' and a.nombre='General (compromisos)' limit 1) where titulo='Sanear la situación financiera integral de EMAVERDE' and (codigo is null or codigo='');
